name: 🔍 PR Code Quality Check

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write
  issues: write
  checks: write

jobs:
  code-quality:
    runs-on: ubuntu-latest
    name: 📋 Analyze Code Quality
    
    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4
      
    - name: 🐍 Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
        
    - name: 📦 Install tools
      run: |
        python -m pip install --upgrade pip
        pip install black pylint mypy
        
    - name: 🎨 Check Black formatting
      id: black-check
      run: |
        echo "## 🎨 Black Formatting Check" >> $GITHUB_STEP_SUMMARY
        
        if black --check --diff . > black_output.txt 2>&1; then
          echo "✅ **Code is properly formatted**" >> $GITHUB_STEP_SUMMARY
          echo "black_status=✅ Passed" >> $GITHUB_OUTPUT
        else
          echo "❌ **Formatting issues found**" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Run \`black .\` to fix formatting:" >> $GITHUB_STEP_SUMMARY
          echo '```diff' >> $GITHUB_STEP_SUMMARY
          cat black_output.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "black_status=❌ Failed" >> $GITHUB_OUTPUT
        fi
        
    - name: 🔍 Check mypy types
      id: mypy-check
      run: |
        echo "## 🔍 mypy Type Checking" >> $GITHUB_STEP_SUMMARY
        
        if mypy --ignore-missing-imports --no-strict-optional . > mypy_output.txt 2>&1; then
          echo "✅ **No type issues found**" >> $GITHUB_STEP_SUMMARY
          echo "mypy_status=✅ Clean" >> $GITHUB_OUTPUT
        else
          echo "⚠️ **Type checking issues found:**" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat mypy_output.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "mypy_status=⚠️ Issues found" >> $GITHUB_OUTPUT
        fi
        
    - name: 📊 Run Pylint analysis
      id: pylint-check
      run: |
        echo "## 📊 Pylint Code Quality Analysis" >> $GITHUB_STEP_SUMMARY
        
        # Запускаем pylint и сохраняем результат (не блокируем при ошибках)
        pylint --output-format=text --reports=no --score=yes **/*.py > pylint_output.txt 2>&1 || true
        
        # Извлекаем оценку
        SCORE=$(grep "Your code has been rated at" pylint_output.txt | grep -o '[0-9]\+\.[0-9]\+' | head -1)
        
        if [[ -n "$SCORE" ]]; then
          echo "📊 **Pylint Score: $SCORE/10.0**" >> $GITHUB_STEP_SUMMARY
          
          # Определяем статус по оценке
          if (( $(echo "$SCORE >= 8.0" | bc -l) )); then
            echo "🌟 **Excellent code quality!**" >> $GITHUB_STEP_SUMMARY
            echo "pylint_status=🌟 Excellent ($SCORE/10)" >> $GITHUB_OUTPUT
          elif (( $(echo "$SCORE >= 7.0" | bc -l) )); then
            echo "✅ **Good code quality**" >> $GITHUB_STEP_SUMMARY
            echo "pylint_status=✅ Good ($SCORE/10)" >> $GITHUB_OUTPUT
          elif (( $(echo "$SCORE >= 5.0" | bc -l) )); then
            echo "⚠️ **Code quality needs improvement**" >> $GITHUB_STEP_SUMMARY
            echo "pylint_status=⚠️ Needs improvement ($SCORE/10)" >> $GITHUB_OUTPUT
          else
            echo "❌ **Poor code quality**" >> $GITHUB_STEP_SUMMARY
            echo "pylint_status=❌ Poor ($SCORE/10)" >> $GITHUB_OUTPUT
          fi
          
          # Показываем детали если есть проблемы
          if grep -q "************* Module" pylint_output.txt; then
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### 📋 Detailed Issues:" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            cat pylint_output.txt >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
          fi
        else
          echo "❌ **Could not determine Pylint score**" >> $GITHUB_STEP_SUMMARY
          echo "pylint_status=❌ Error" >> $GITHUB_OUTPUT
        fi
        
    - name: 📝 Create PR comment
      uses: actions/github-script@v7
      if: github.event_name == 'pull_request'
      with:
        script: |
          const blackStatus = '${{ steps.black-check.outputs.black_status }}';
          const mypyStatus = '${{ steps.mypy-check.outputs.mypy_status }}';
          const pylintStatus = '${{ steps.pylint-check.outputs.pylint_status }}';
          
          const comment = `## 🔍 Code Quality Report
          
          | Tool | Status | Description |
          |------|--------|-------------|
          | 🎨 **Black** | ${blackStatus} | Auto-formatting check |
          | 🔍 **mypy** | ${mypyStatus} | Type checking |
          | 📊 **Pylint** | ${pylintStatus} | Code quality analysis |
          
          ### 💡 How to fix issues:
          \`\`\`bash
          # Fix formatting
          black .
          
          # Check types  
          mypy .
          
          # Analyze quality
          pylint your_file.py
          \`\`\`
          
          ### 🎯 Quality Guidelines:
          - **Black**: Auto-formats code (run locally)
          - **mypy**: Add type hints for better code
          - **Pylint**: Aim for 8.0+ score for excellent quality
          
          ---
          *This check runs automatically on every PR. Issues don't block merge, but fixing them improves code quality! 🚀*`;
          
          // Найти существующий комментарий или создать новый
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          });
          
          const botComment = comments.find(comment => 
            comment.user.type === 'Bot' && comment.body.includes('🔍 Code Quality Report')
          );
          
          if (botComment) {
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: botComment.id,
              body: comment
            });
          } else {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: comment
            });
          } 